### PR TITLE
Remove gmp (it is already a mpfr dependency) and mpir (deprecated and unmaintained)

### LINKED ISSUE #55: Explicit GMP/MPIR dependency
This is based on the discussion in https://github.com/conda-forge/gudhi-feedstock/pull/52. Since it isn't something we will handle immediately, I am writing it in an issue so it isn't lost.
Our meta.yaml now explicitly lists
```
    - gmp   # [unix]
    - mpfr
    - mpir  # [win]
    - ucrt  # [win]
```
Duplicating this information from cgal-cpp looks like a bad practice. If cgal-cpp moves to using gmp on windows as well, or starts using its no-GMP mode, gudhi will be out of sync.

We should investigate if those dependencies could be generated automatically somehow (this could imply some modifications in cgal-cpp).

### PR DESCRIPTION
**Pull request by VincentRouvreau**
… unmaintained)

Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

Replace #62 
Fix partially #55

### CODE REVIEW

**Comment by mglisse** [comment]
I don't think #55 should be closed after this: it also wants to remove mpfr (and ucrt?), which is harder.

**Comment by mglisse** [comment]
It seems that all the errors are with pypy, but looking at more recent PRs this has been removed from conda-forge (https://conda-forge.org/news/2024/08/14/sunsetting-pypy/), so it may be enough to regenerate the files (rerender?).

**Comment by VincentRouvreau** [comment]
> I don't think #55 should be closed after this: it also wants to remove mpfr (and ucrt?), which is harder.

Ok, I removed the automatic close of the issue

**Comment by VincentRouvreau** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
